GET http://localhost:4000
###
GET http://localhost:4000/codeBlock
###
GET http://localhost:4000/codeBlock/63da9c5f26973dd702cd27c3
###
POST http://localhost:4000/codeBlock 
content-type: application/json

{
  "title": "For Loop",
  "code": "code .....",
  "href": "/forLoop"
}