import React from 'react';
import Head from 'next/head';
import style from '../../styles/codeBlockPage.module.scss';

export async function getServerSideProps(context: any) {
  const { params } = context;
  const response = await fetch(`http://localhost:4000/codeBlock/${params.id}`);
  const data = await response.json();

  // will be passed to the page component as props
  return {
    props: {
      codeBlock: data.data
    },
  }
}

function CodeBlock({ codeBlock }: any) {
  return (
    <div className={style.codeBlockPage}>
      <Head>
        <title>{codeBlock.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>{codeBlock.title}</h1>
      <textarea />
    </div>
  )
}

export default CodeBlock;